### PR TITLE
Use OPENVIZSLA_EXPORT macro in ov.h

### PR DESCRIPTION
**Pull request by desowin**
This fixes compilation error while building libopenvizsla using vcpkg.

I cannot get the unit tests to build using vcpkg. I got the library to build with vcpkg when I simply removed the tests from CMakeLists.txt.

### CODE REVIEW

**Comment by matwey** [comment]
`openvizsla_export.h` definitely must not be a part of the public interface. What issue do you try to solve? Everything seems to build fine with VS 2015 and 2019 for me.

**Comment by desowin** [comment]
> `openvizsla_export.h` definitely must not be a part of the public interface. What issue do you try to solve? Everything seems to build fine with VS 2015 and 2019 for me.

CMake documentation seems to disagree: "The resulting file should be installed with other headers in the library." [1]

The problem this fixes is:
```
     5>C:\Development\vcpkg\buildtrees\libopenvizsla\src\0.1.0-rc2-849b5d1270\src\ov.c(110,19): error C2375: 'ov_new': redefinition; different linkage [C:\Development\vcpkg\buildtrees\libopenvizsla\x86-windows-dbg\openvizsla.vcxproj]
       C:\Development\vcpkg\buildtrees\libopenvizsla\src\0.1.0-rc2-849b5d1270\include\ov.h(53): message : see declaration of 'ov_new' [C:\Development\vcpkg\buildtrees\libopenvizsla\x86-windows-dbg\openvizsla.vcxproj]
     5>C:\Development\vcpkg\buildtrees\libopenvizsla\src\0.1.0-rc2-849b5d1270\src\ov.c(153,5): error C2375: 'ov_open': redefinition; different linkage [C:\Development\vcpkg\buildtrees\libopenvizsla\x86-windows-dbg\openvizsla.vcxproj]
       C:\Development\vcpkg\buildtrees\libopenvizsla\src\0.1.0-rc2-849b5d1270\include\ov.h(54): message : see declaration of 'ov_open' [C:\Development\vcpkg\buildtrees\libopenvizsla\x86-windows-dbg\openvizsla.vcxproj]
     5>C:\Development\vcpkg\buildtrees\libopenvizsla\src\0.1.0-rc2-849b5d1270\src\ov.c(204,6): error C2375: 'ov_free': redefinition; different linkage [C:\Development\vcpkg\buildtrees\libopenvizsla\x86-windows-dbg\openvizsla.vcxproj]
       C:\Development\vcpkg\buildtrees\libopenvizsla\src\0.1.0-rc2-849b5d1270\include\ov.h(55): message : see declaration of 'ov_free' [C:\Development\vcpkg\buildtrees\libopenvizsla\x86-windows-dbg\openvizsla.vcxproj]
     5>C:\Development\vcpkg\buildtrees\libopenvizsla\src\0.1.0-rc2-849b5d1270\src\ov.c(212,5): error C2375: 'ov_get_usb_speed': redefinition; different linkage [C:\Development\vcpkg\buildtrees\libopenvizsla\x86-windows-dbg\openvizsla.vcxproj]
       C:\Development\vcpkg\buildtrees\libopenvizsla\src\0.1.0-rc2-849b5d1270\include\ov.h(57): message : see declaration of 'ov_get_usb_speed' [C:\Development\vcpkg\buildtrees\libopenvizsla\x86-windows-dbg\openvizsla.vcxproj]
     5>C:\Development\vcpkg\buildtrees\libopenvizsla\src\0.1.0-rc2-849b5d1270\src\ov.c(225,5): error C2375: 'ov_set_usb_speed': redefinition; different linkage [C:\Development\vcpkg\buildtrees\libopenvizsla\x86-windows-dbg\openvizsla.vcxproj]
       C:\Development\vcpkg\buildtrees\libopenvizsla\src\0.1.0-rc2-849b5d1270\include\ov.h(58): message : see declaration of 'ov_set_usb_speed' [C:\Development\vcpkg\buildtrees\libopenvizsla\x86-windows-dbg\openvizsla.vcxproj]
     5>C:\Development\vcpkg\buildtrees\libopenvizsla\src\0.1.0-rc2-849b5d1270\src\ov.c(238,5): error C2375: 'ov_capture_start': redefinition; different linkage [C:\Development\vcpkg\buildtrees\libopenvizsla\x86-windows-dbg\openvizsla.vcxproj]
       C:\Development\vcpkg\buildtrees\libopenvizsla\src\0.1.0-rc2-849b5d1270\include\ov.h(60): message : see declaration of 'ov_capture_start' [C:\Development\vcpkg\buildtrees\libopenvizsla\x86-windows-dbg\openvizsla.vcxproj]
     5>C:\Development\vcpkg\buildtrees\libopenvizsla\src\0.1.0-rc2-849b5d1270\src\ov.c(262,5): error C2375: 'ov_capture_dispatch': redefinition; different linkage [C:\Development\vcpkg\buildtrees\libopenvizsla\x86-windows-dbg\openvizsla.vcxproj]
       C:\Development\vcpkg\buildtrees\libopenvizsla\src\0.1.0-rc2-849b5d1270\include\ov.h(61): message : see declaration of 'ov_capture_dispatch' [C:\Development\vcpkg\buildtrees\libopenvizsla\x86-windows-dbg\openvizsla.vcxproj]
     5>C:\Development\vcpkg\buildtrees\libopenvizsla\src\0.1.0-rc2-849b5d1270\src\ov.c(273,5): error C2375: 'ov_capture_stop': redefinition; different linkage [C:\Development\vcpkg\buildtrees\libopenvizsla\x86-windows-dbg\openvizsla.vcxproj]
       C:\Development\vcpkg\buildtrees\libopenvizsla\src\0.1.0-rc2-849b5d1270\include\ov.h(62): message : see declaration of 'ov_capture_stop' [C:\Development\vcpkg\buildtrees\libopenvizsla\x86-windows-dbg\openvizsla.vcxproj]
     5>C:\Development\vcpkg\buildtrees\libopenvizsla\src\0.1.0-rc2-849b5d1270\src\ov.c(283,5): error C2375: 'ov_load_firmware': redefinition; different linkage [C:\Development\vcpkg\buildtrees\libopenvizsla\x86-windows-dbg\openvizsla.vcxproj]
       C:\Development\vcpkg\buildtrees\libopenvizsla\src\0.1.0-rc2-849b5d1270\include\ov.h(64): message : see declaration of 'ov_load_firmware' [C:\Development\vcpkg\buildtrees\libopenvizsla\x86-windows-dbg\openvizsla.vcxproj]
     5>C:\Development\vcpkg\buildtrees\libopenvizsla\src\0.1.0-rc2-849b5d1270\src\ov.c(325,13): error C2375: 'ov_get_error_string': redefinition; different linkage [C:\Development\vcpkg\buildtrees\libopenvizsla\x86-windows-dbg\openvizsla.vcxproj]
       C:\Development\vcpkg\buildtrees\libopenvizsla\src\0.1.0-rc2-849b5d1270\include\ov.h(66): message : see declaration of 'ov_get_error_string' [C:\Development\vcpkg\buildtrees\libopenvizsla\x86-windows-dbg\openvizsla.vcxproj]
     5>Done Building Project "C:\Development\vcpkg\buildtrees\libopenvizsla\x86-windows-dbg\openvizsla.vcxproj" (default targets) -- FAILED.
```

[1] https://cmake.org/cmake/help/v3.7/module/GenerateExportHeader.html

**Comment by matwey** [comment]
What was the command to produce this output?

**Comment by desowin** [comment]
> What was the command to produce this output?

vcpkg install libopenvizsla

The port file is essentially same as in https://github.com/desowin/vcpkg/tree/libopenvizsla but with the different git REF value (and due to that the SHA512).

**Comment by matwey** [comment]
You are right. `-DBUILD_SHARED_LIBS=ON` is broken for Windows (MS VS) and never worked before.

**Pull request merged**
