### PR TITLE
Add initial implementation for macos support

### PR DESCRIPTION
**Pull request by matwey**
Close #18

### CODE REVIEW

**Comment by matwey** [comment]
@fjolnir could you please check, if it works for you?

**Comment by matwey** [comment]
CI is failed due to https://github.com/appveyor/ci/issues/3326

**Comment by fjolnir** [comment]
Doesn't appear to work, fw init fails, and `otool -s __DATA __ov3_fwpkg libopenvizsla.a` returns nothing.

**Comment by fjolnir** [comment]
It is present in the sample binaries though, just doesn't get added to the archive.

**Comment by matwey** [comment]
> Doesn't appear to work, fw init fails, and `otool -s __DATA __ov3_fwpkg libopenvizsla.a` returns nothing.

That is quite strange. I've tested both 10.15 and 10.14: fw unit test passed ok.

Also, `otool -s __DATA __ov3_fwpkg` should return the thing for binaries or `libopenvizsla.so`.

**Comment by desowin** [comment]
When linking statically, the binaries do include `__ov3_fwpkg` and `libopenvizsla.a` doesn't include `__ov3_fwpkg`.

When building as dynamic library, using `cmake -DBUILD_SHARED_LIBS=ON ~/dev/libopenvizsla`, then it is included in `libopenvizsla.dylib` and `otool -s __DATA __ov3_fwpkg libopenvizsla.dylib` shows firmware data.

`ovextcap` works just fine on Mac OS Catalina 10.15.4.

**Comment by fjolnir** [comment]
Isn't the issue just that you can't add sections to an archive?

**Pull request merged**
