### PR TITLE
Use speed specific linktypes in ovextcap

### PR DESCRIPTION
**Pull request by desowin**
Capture speed is retained when speed specific linktype is used. Add the
option to use former, deprecated linktype useful when ovextcap is used
with Wireshark version that does not understand new linktypes.

MUST NOT be merged before https://github.com/the-tcpdump-group/libpcap/pull/1109 and https://github.com/the-tcpdump-group/tcpdump-htdocs/pull/29

### CODE REVIEW

**Comment by desowin** [comment]
Requires Wireshark with [USBLL: Dissect speed specific linktypes](https://gitlab.com/wireshark/wireshark/-/merge_requests/7045) applied

**Comment by matwey** [comment]
Is it possible to detect actual WireShark version and behave accordingly?

**Comment by desowin** [comment]
> Is it possible to detect actual WireShark version and behave accordingly?

This implementation handles it with an boolean flag that user should set if using older version (or if just wants old linktype). This allows getting working live capture with older Wireshark (that is, the Wireshark will understand the linktype) if the user manually checks the option to use deprecated linktype.

An alternative approach would be to detect Wireshark version and act accordingly. The new linktype won't work before major release (unless we decide to not quite care about compatibility with 3.7.0), but considering 4.0 is not that far off it might be worth a shot. The version detection can be accomplished by making use of `--extcap-interfaces --extcap-version X.X` where `X.X` is Wireshark version, currently 3.7 in master branch. If `ovextcap` detects Wireshark version greater than first one supporting new linktypes, it would simply return new interface list (currently the interface is simply named `ov`). Then during capture we would know Wireshark version from the `--extcap-interface` parameter.

**Comment by matwey** [comment]
Could you please rebase on master? I've fixed CI.

**Comment by desowin** [comment]
@matwey Now that the Wireshark 4.0 is released, could you please review it again?

**Comment by matwey** [comment]
Thanks!

**Pull request merged**
